USE QuanLyBenhVienDb;
GO

INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 1', N'Nam', 30, 'DS1', '');
DECLARE @Pid1 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid1, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 2', N'Nam', 30, 'DS2', '');
DECLARE @Pid2 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid2, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 3', N'Nam', 30, 'DS3', '');
DECLARE @Pid3 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid3, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 4', N'Nam', 30, 'DS4', '');
DECLARE @Pid4 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid4, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 5', N'Nam', 30, 'DS5', '');
DECLARE @Pid5 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid5, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 6', N'Nam', 30, 'DS6', '');
DECLARE @Pid6 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid6, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n chá» khÃ¡m 7', N'Nam', 30, 'DS7', '');
DECLARE @Pid7 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid7, N'Äau Ä‘áº§u', GETDATE(), 1);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 1', N'Ná»¯', 40, 'HS1', '');
DECLARE @Pid_HS1 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS1, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS1 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS1, N'Triá»‡u chá»©ng 1', N'Cháº©n Ä‘oÃ¡n 1', N'Äiá»u trá»‹ 1', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 2', N'Ná»¯', 40, 'HS2', '');
DECLARE @Pid_HS2 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS2, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS2 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS2, N'Triá»‡u chá»©ng 2', N'Cháº©n Ä‘oÃ¡n 2', N'Äiá»u trá»‹ 2', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 3', N'Ná»¯', 40, 'HS3', '');
DECLARE @Pid_HS3 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS3, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS3 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS3, N'Triá»‡u chá»©ng 3', N'Cháº©n Ä‘oÃ¡n 3', N'Äiá»u trá»‹ 3', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 4', N'Ná»¯', 40, 'HS4', '');
DECLARE @Pid_HS4 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS4, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS4 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS4, N'Triá»‡u chá»©ng 4', N'Cháº©n Ä‘oÃ¡n 4', N'Äiá»u trá»‹ 4', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 5', N'Ná»¯', 40, 'HS5', '');
DECLARE @Pid_HS5 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS5, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS5 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS5, N'Triá»‡u chá»©ng 5', N'Cháº©n Ä‘oÃ¡n 5', N'Äiá»u trá»‹ 5', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 6', N'Ná»¯', 40, 'HS6', '');
DECLARE @Pid_HS6 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS6, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS6 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS6, N'Triá»‡u chá»©ng 6', N'Cháº©n Ä‘oÃ¡n 6', N'Äiá»u trá»‹ 6', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 7', N'Ná»¯', 40, 'HS7', '');
DECLARE @Pid_HS7 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS7, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS7 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS7, N'Triá»‡u chá»©ng 7', N'Cháº©n Ä‘oÃ¡n 7', N'Äiá»u trá»‹ 7', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 8', N'Ná»¯', 40, 'HS8', '');
DECLARE @Pid_HS8 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS8, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS8 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS8, N'Triá»‡u chá»©ng 8', N'Cháº©n Ä‘oÃ¡n 8', N'Äiá»u trá»‹ 8', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 9', N'Ná»¯', 40, 'HS9', '');
DECLARE @Pid_HS9 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS9, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS9 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS9, N'Triá»‡u chá»©ng 9', N'Cháº©n Ä‘oÃ¡n 9', N'Äiá»u trá»‹ 9', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 10', N'Ná»¯', 40, 'HS10', '');
DECLARE @Pid_HS10 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS10, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS10 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS10, N'Triá»‡u chá»©ng 10', N'Cháº©n Ä‘oÃ¡n 10', N'Äiá»u trá»‹ 10', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 11', N'Ná»¯', 40, 'HS11', '');
DECLARE @Pid_HS11 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS11, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS11 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS11, N'Triá»‡u chá»©ng 11', N'Cháº©n Ä‘oÃ¡n 11', N'Äiá»u trá»‹ 11', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 12', N'Ná»¯', 40, 'HS12', '');
DECLARE @Pid_HS12 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS12, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS12 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS12, N'Triá»‡u chá»©ng 12', N'Cháº©n Ä‘oÃ¡n 12', N'Äiá»u trá»‹ 12', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 13', N'Ná»¯', 40, 'HS13', '');
DECLARE @Pid_HS13 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS13, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS13 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS13, N'Triá»‡u chá»©ng 13', N'Cháº©n Ä‘oÃ¡n 13', N'Äiá»u trá»‹ 13', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 14', N'Ná»¯', 40, 'HS14', '');
DECLARE @Pid_HS14 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS14, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS14 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS14, N'Triá»‡u chá»©ng 14', N'Cháº©n Ä‘oÃ¡n 14', N'Äiá»u trá»‹ 14', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 15', N'Ná»¯', 40, 'HS15', '');
DECLARE @Pid_HS15 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS15, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS15 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS15, N'Triá»‡u chá»©ng 15', N'Cháº©n Ä‘oÃ¡n 15', N'Äiá»u trá»‹ 15', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 16', N'Ná»¯', 40, 'HS16', '');
DECLARE @Pid_HS16 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS16, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS16 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS16, N'Triá»‡u chá»©ng 16', N'Cháº©n Ä‘oÃ¡n 16', N'Äiá»u trá»‹ 16', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 17', N'Ná»¯', 40, 'HS17', '');
DECLARE @Pid_HS17 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS17, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS17 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS17, N'Triá»‡u chá»©ng 17', N'Cháº©n Ä‘oÃ¡n 17', N'Äiá»u trá»‹ 17', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 18', N'Ná»¯', 40, 'HS18', '');
DECLARE @Pid_HS18 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS18, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS18 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS18, N'Triá»‡u chá»©ng 18', N'Cháº©n Ä‘oÃ¡n 18', N'Äiá»u trá»‹ 18', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 19', N'Ná»¯', 40, 'HS19', '');
DECLARE @Pid_HS19 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS19, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS19 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS19, N'Triá»‡u chá»©ng 19', N'Cháº©n Ä‘oÃ¡n 19', N'Äiá»u trá»‹ 19', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n khÃ¡m xong 20', N'Ná»¯', 40, 'HS20', '');
DECLARE @Pid_HS20 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_HS20, N'KhÃ¡m Ä‘á»‹nh ká»³', GETDATE(), 4);
DECLARE @Aid_HS20 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, CreatedAt, IsLocked) VALUES (@Aid_HS20, N'Triá»‡u chá»©ng 20', N'Cháº©n Ä‘oÃ¡n 20', N'Äiá»u trá»‹ 20', GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 1', N'Nam', 50, 'NT1', '');
DECLARE @Pid_NT1 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT1, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT1 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT1, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 1, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 2', N'Nam', 50, 'NT2', '');
DECLARE @Pid_NT2 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT2, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT2 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT2, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 2, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 3', N'Nam', 50, 'NT3', '');
DECLARE @Pid_NT3 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT3, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT3 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT3, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 3, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 4', N'Nam', 50, 'NT4', '');
DECLARE @Pid_NT4 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT4, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT4 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT4, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 4, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 5', N'Nam', 50, 'NT5', '');
DECLARE @Pid_NT5 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT5, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT5 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT5, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 5, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 6', N'Nam', 50, 'NT6', '');
DECLARE @Pid_NT6 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT6, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT6 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT6, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 6, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 7', N'Nam', 50, 'NT7', '');
DECLARE @Pid_NT7 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT7, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT7 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT7, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 7, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 8', N'Nam', 50, 'NT8', '');
DECLARE @Pid_NT8 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT8, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT8 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT8, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 8, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 9', N'Nam', 50, 'NT9', '');
DECLARE @Pid_NT9 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT9, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT9 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT9, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 9, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 10', N'Nam', 50, 'NT10', '');
DECLARE @Pid_NT10 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT10, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT10 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT10, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 10, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 11', N'Nam', 50, 'NT11', '');
DECLARE @Pid_NT11 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT11, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT11 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT11, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 11, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 12', N'Nam', 50, 'NT12', '');
DECLARE @Pid_NT12 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT12, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT12 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT12, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 12, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 13', N'Nam', 50, 'NT13', '');
DECLARE @Pid_NT13 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT13, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT13 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT13, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 13, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 14', N'Nam', 50, 'NT14', '');
DECLARE @Pid_NT14 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT14, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT14 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT14, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 14, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 15', N'Nam', 50, 'NT15', '');
DECLARE @Pid_NT15 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT15, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT15 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT15, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 15, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 16', N'Nam', 50, 'NT16', '');
DECLARE @Pid_NT16 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT16, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT16 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT16, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 16, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 17', N'Nam', 50, 'NT17', '');
DECLARE @Pid_NT17 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT17, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT17 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT17, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 17, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 18', N'Nam', 50, 'NT18', '');
DECLARE @Pid_NT18 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT18, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT18 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT18, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 18, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 19', N'Nam', 50, 'NT19', '');
DECLARE @Pid_NT19 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT19, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT19 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT19, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 19, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 20', N'Nam', 50, 'NT20', '');
DECLARE @Pid_NT20 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT20, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT20 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT20, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 20, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 21', N'Nam', 50, 'NT21', '');
DECLARE @Pid_NT21 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT21, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT21 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT21, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 21, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 22', N'Nam', 50, 'NT22', '');
DECLARE @Pid_NT22 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT22, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT22 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT22, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 22, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 23', N'Nam', 50, 'NT23', '');
DECLARE @Pid_NT23 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT23, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT23 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT23, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 23, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 24', N'Nam', 50, 'NT24', '');
DECLARE @Pid_NT24 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT24, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT24 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT24, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 24, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 25', N'Nam', 50, 'NT25', '');
DECLARE @Pid_NT25 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT25, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT25 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT25, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 25, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 26', N'Nam', 50, 'NT26', '');
DECLARE @Pid_NT26 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT26, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT26 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT26, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 26, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 27', N'Nam', 50, 'NT27', '');
DECLARE @Pid_NT27 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT27, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT27 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT27, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 27, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 28', N'Nam', 50, 'NT28', '');
DECLARE @Pid_NT28 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT28, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT28 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT28, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 28, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 29', N'Nam', 50, 'NT29', '');
DECLARE @Pid_NT29 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT29, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT29 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT29, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 29, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 30', N'Nam', 50, 'NT30', '');
DECLARE @Pid_NT30 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT30, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT30 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT30, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 30, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 31', N'Nam', 50, 'NT31', '');
DECLARE @Pid_NT31 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT31, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT31 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT31, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 31, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 32', N'Nam', 50, 'NT32', '');
DECLARE @Pid_NT32 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT32, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT32 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT32, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 32, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 33', N'Nam', 50, 'NT33', '');
DECLARE @Pid_NT33 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT33, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT33 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT33, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 33, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 34', N'Nam', 50, 'NT34', '');
DECLARE @Pid_NT34 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT34, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT34 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT34, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 34, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 35', N'Nam', 50, 'NT35', '');
DECLARE @Pid_NT35 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT35, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT35 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT35, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 35, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 36', N'Nam', 50, 'NT36', '');
DECLARE @Pid_NT36 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT36, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT36 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT36, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 36, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 37', N'Nam', 50, 'NT37', '');
DECLARE @Pid_NT37 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT37, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT37 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT37, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 37, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 38', N'Nam', 50, 'NT38', '');
DECLARE @Pid_NT38 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT38, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT38 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT38, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 38, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 39', N'Nam', 50, 'NT39', '');
DECLARE @Pid_NT39 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT39, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT39 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT39, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 39, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 40', N'Nam', 50, 'NT40', '');
DECLARE @Pid_NT40 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT40, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT40 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT40, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 40, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 41', N'Nam', 50, 'NT41', '');
DECLARE @Pid_NT41 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT41, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT41 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT41, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 41, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 42', N'Nam', 50, 'NT42', '');
DECLARE @Pid_NT42 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT42, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT42 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT42, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 42, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 43', N'Nam', 50, 'NT43', '');
DECLARE @Pid_NT43 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT43, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT43 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT43, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 43, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 44', N'Nam', 50, 'NT44', '');
DECLARE @Pid_NT44 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT44, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT44 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT44, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 44, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 45', N'Nam', 50, 'NT45', '');
DECLARE @Pid_NT45 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT45, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT45 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT45, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 45, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 46', N'Nam', 50, 'NT46', '');
DECLARE @Pid_NT46 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT46, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT46 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT46, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 46, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 47', N'Nam', 50, 'NT47', '');
DECLARE @Pid_NT47 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT47, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT47 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT47, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 47, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 48', N'Nam', 50, 'NT48', '');
DECLARE @Pid_NT48 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT48, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT48 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT48, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 1, 48, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 49', N'Nam', 50, 'NT49', '');
DECLARE @Pid_NT49 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT49, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT49 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT49, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 2, 49, GETDATE(), 0);
INSERT INTO Patients (FullName, Gender, Age, PatientCode, Allergies) VALUES (N'Bá»‡nh nhÃ¢n ná»™i trÃº 50', N'Nam', 50, 'NT50', '');
DECLARE @Pid_NT50 INT = SCOPE_IDENTITY();
INSERT INTO Appointments (PatientId, Reason, AppointmentTime, Status) VALUES (@Pid_NT50, N'Cáº¥p cá»©u', GETDATE(), 4);
DECLARE @Aid_NT50 INT = SCOPE_IDENTITY();
INSERT INTO MedicalRecords (AppointmentId, Symptoms, Diagnosis, TreatmentPlan, AdmissionDate, DepartmentId, BedNumber, CreatedAt, IsLocked) VALUES (@Aid_NT50, N'Triá»‡u chá»©ng náº·ng', N'Nháº­p viá»‡n', N'Theo dÃµi', GETDATE(), 3, 50, GETDATE(), 0);
GO

